#!/usr/bin/env bash
# configures a new Ubuntu machine to task requirements
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y nginx
sudo service nginx start
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html