#!/usr/bin/env bash
# prints Holberton School 10x, but prints bad luck on 4 and good luck on 8
c=1
while [ $c -le 10 ]
do
	if [ $c == 4 ]
	then
		echo "bad luck"
	elif [ $c == 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	(( c++ ))
done
